[package]
name = "kv_storage"
version = "0.1.0"
edition = "2021"


# Dependencies
[dependencies]
libp2p = "0.43.0"
futures = "0.3.21"
async-std = { version = "1.10.0", features = ["attributes"] }
tokio = "1.41.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.11"