[package]
name = "kv_storage"
version = "0.1.0"
edition = "2021"


# Dependencies
[dependencies]
libp2p = "0.39.1"
futures = "0.3.15"
env_logger = "0.9.0"
async-std = { version = "1.9.0", features = ["attributes"] }
clap = { version = "4.4", features = ["derive"] }
rustyline = "10.0"