[package]
name = "kv_storage"
version = "0.1.0"
edition = "2021"

# Dependencies
[dependencies]
libp2p = { version = "0.42.2", features = ["tcp-tokio", "dns-tokio"] }
async-std = "1.10" 
futures = "0.3"
